### ISSUE TITLE
Adicionar Switch case no controller

### ISSUE THREAD

**Issue by arthurs159** [adautob/clientes-web#1]
Oi Adauto, tudo bom?

Olhando seu projeto, acredito que seja uma boa opção utilizar o switch-case para casos em que você tenha que colocar muitos if's no projeto, digo nessa parte aqui na imagem abaixo:
![image](https://user-images.githubusercontent.com/77133022/194669083-f9687753-ec48-49f5-b618-7123d5fe1467.png)

**Comment by adautob** [comment]
Atualizado código conforme sugestão.
![issue_resolvida](https://user-images.githubusercontent.com/95452249/194763559-ce6d5cf8-843c-434b-b434-ca1efbdf08c0.png)
