### ISSUE TITLE
Melhorar o Readme

### ISSUE THREAD

**Issue by arthurs159** [adautob/clientes-web#2]
Olhando seu projeto, percebi que está faltando algumas coisas no readme e ele é o primeiro contato com o projeto que qualquer pessoa vai ter, e muitas vezes o recrutador nem sabe codar, então ele não irá baixar seu projeto para testar. Isso faz o readme mais importante ainda. Eu recomendo colocar um briefing do projeto, quais foram os seus objetivos ao fazer esse projeto, porque decidiu fazer ele, uma fotos de como ficou o resultado, e pelo menos 3 coisas que aprendeu ao fazer esse projeto.

Qualquer dúvida só me chamar!! : )

**Comment by adautob** [comment]
Readme atualizado utlizando sua recomendações Arthur, obrigado pela sua contribuição!
